### ISSUE TITLE
Any tutorials available ?

### ISSUE THREAD

**Issue by kcvinker** [Rayerd/dfl#53]
Hi, 
I want to try some gui (windows only) programs in D. How to install this library ? And how to use this ? Can i get a tutorial or sample code ? Thanks in advance.

**Comment by vinodvinu** [comment]
Closing this because i dont think i will get an answer.

**Comment by DeenOConnor** [comment]
http://wiki.dprogramming.com/Dfl/Tutorial

**Comment by kcvinker** [comment]
@DeenOConnor 
My last comment was on 2021 Jan. In these 2 years, I wrote my own GUI lib in D.

**Comment by DeenOConnor** [comment]
Well, i saw everyone stop working on dfl and finally decided to do it myself...
To only come here and realize that apparently i could've just cloned this repo, because it came back to life
Will check you library out, thanks

**Comment by Rayerd** [comment]
Hello!
I decided to continue developing for a while.

**Comment by kcvinker** [comment]
@DeenOConnor Thank you for your good words. Please don't let this project die.

**Comment by Rayerd** [comment]
Not a tutorial, but sample code can be found here.
https://github.com/Rayerd/dfl/tree/master/examples
