### ISSUE TITLE
Plans to implement Anchor?

### ISSUE THREAD

**Issue by Dadoum** [Rayerd/dfl#54]
In the code there are some signs that an `anchor` property was planned, and it would have been very useful for layout.

Is there any plan to implement the property?

EDIT: uncommenting the associated code and adding a small `scope(exit)` to fix the issue pointed out in the onLayout function makes it work.

**Comment by Rayerd** [comment]
I don't understand why the code related to anchor properties is commented out or marked as deprecated.
It seems like they switched to using dock properties during development.
I think it would be nice to have an anchor property, but I don't plan on implementing it for a while.

**Comment by Dadoum** [comment]
I guess I will have to fork the project and uncomment the code. Thanks for your quick response!

**Comment by Rayerd** [comment]
I added locationAlignment!
It is similar to anchor.
