### ISSUE TITLE
Feature Request:Entice update

### ISSUE THREAD

**Issue by LukyGuyLucky** [Rayerd/dfl#55]
It is really great to see DFL has been updated and maintained.I am wondering whether the designer Entice [
[http://www.dprogramming.com/entice.php](url) is supposed to be updated as well.The original is lack of utf8 support for the source editor ,and sure other things.

Thanks and best regards.

**Comment by Rayerd** [comment]
Entice Designer is an interesting piece of software.
Its functionality as a GUI builder may still be useful, but its functionality as a source editor should be replaced by VSCode.
For the time being, I have no plans to update Entice Designer.

**Comment by LukyGuyLucky** [comment]
Thanks for the feeback.
